name: int_phone_text_field
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
